apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: online-boutique
  labels:
    app: productcatalogservice
    cluster: obs-challenge-c2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
        cluster: obs-challenge-c2
    spec:
      containers:
        - name: productcatalogservice
          image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.1
          ports:
            - containerPort: 3550
              protocol: TCP
          env:
            - name: PORT
              value: "3550"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            grpc:
              port: 3550
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 3550
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: online-boutique
  labels:
    app: productcatalogservice
    cluster: obs-challenge-c2
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
    - port: 3550
      targetPort: 3550
      protocol: TCP
      name: grpc
